### ISSUE TITLE
Can interaction fingerprints indicate which residues are involved

### ISSUE THREAD

**Issue by syedzayyan** [chemosim-lab/ProLIF#145]
Hello,

Apologies for this noob question. Can only a fingerprint indicate which residues are involved in a protein-ligand interaction?  I was guessing a 0 would indicate absence of an interaction and a 1 the presence.

**Comment by cbouy** [comment]
Not sure if I understand your question correctly, do you mean to ask if there are any other methods to detect which residues are involved in interactions between a protein and a ligand?

> a 0 would indicate absence of an interaction and a 1 the presence.
That is correct

**Comment by syedzayyan** [comment]
Let's say I generate a fingerprint from a protein ligand structure. The fingerprint is a bitvector right? Consisting of 0s and 1s. Can I reconstruct the list of interactions from the fingerprint itself?

Or is the fingerprint processed through a hashing function so there is no inherent meaning to them. Also is the fingerprint fixed length?

**Comment by cbouy** [comment]
Short answer is no (or at least not with only the bitvector)

In order to generate the RDKit bitvector object it first converts the prolif "FP" to a pandas DataFrame, and then creates the bitvector from each row.
So each bit position relates to the corresponding column position in the dataframe, which means that if you save the header of the dataframe, you could map back the bitvector index to a residue and type of interaction.
But to reconstruct the corresponding prolif `Fingerprint` object that would be a bit more involved and depend on internals that are going to change when v2.0 is released so I wouldn't recommend doing that.

What's the use case for this out of curiosity?

**Comment by syedzayyan** [comment]
I presume if the headers are always the same they can be? I am using docked structures, so the protein is always the same, only the ligand changes.

I am trying to replicate [this](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9418666/) paper, where they are statistically analysing interactions. But they are using Arpeggio which uses Python 2.7 and dockerized containers. Neither of which I am willing to touch at the moment.

**Comment by cbouy** [comment]
Yes if the dataframe headers are the same, then you can directly compare the resulting bitvector positions
