### ISSUE TITLE
Analyze Autodock Vina poses.

### ISSUE THREAD

**Issue by Le-Phung-Hien** [chemosim-lab/ProLIF#146]
Hi team,

Thanks for the great tool.

I am trying to streamline my docking analysis. AutoDock Vina results has two pdbqt file, one for different poses of the ligand, and one for the protein. Just want to ask if ProLIF can identify and  virtualize the receptor-ligand interactions with pdbqt files, or I need to convert the ligands to pdb or sdf file?

Thanks!

**Comment by cbouy** [comment]
Hi,

Please refer to the [docking section](https://prolif.readthedocs.io/en/stable/notebooks/how-to.html#Working-with-docking-poses-instead-of-MD-simulations) of the tutorials. Short answer:
- for the protein you'll need a non-PDBQT file (most likely a PDB file) with explicit hydrogens
- for the ligand poses, you can use:
  - the `prolif.pdbqt_supplier(pdbqt_files, template)` function where `pdbqt_files` is a list of paths to each individual pose PDBQT file (which you can obtain with the `vina_split` command), and `template` is an RDKit mol with the correct bond orders and charges (since PDBQT format lacks those).
  - alternatively, you can convert your PDBQT files to an SDF, I think `meeko` does this pretty well (don't use openbabel) and then use `prolif.sdf_supplier`

Please close this issue if this answers your question!

**Comment by Le-Phung-Hien** [comment]
Thank you very much!
