### ISSUE TITLE
New interaction (Backbone NH-Pi )

### ISSUE THREAD

**Issue by DipBobDar** [chemosim-lab/ProLIF#158]
Dear all,

Can you replace the cation in
cation="[+{1-},$([NX3&!$([NX3]-O)]-[C]=[NX3+])]"
with NH from the protein backbone and look for the interaction with any of the pi systems.

Could you may be give me a SMART for such and also is this the only place where the Cation is being initialized.

Thanks in advance for your help

**Comment by cbouy** [comment]
You can have a look at [this tutorial](https://prolif.readthedocs.io/en/stable/notebooks/advanced.html#repurposing-an-existing-interaction) on defining new interactions. 
In the way ProLIF names the interaction classes, if I understand correctly the interaction you'd need to inherit from would be the `PiCation` one (i.e. the "ligand" is the pi-system and the "protein" is the cation).
As for the SMARTS, there's one suggested in the [tutorial on ignoring the backbone](https://prolif.readthedocs.io/en/stable/notebooks/advanced.html#ignoring-the-protein-backbone), you'd need to modify it so that the nitrogen is the first atom appearing in the SMARTS pattern, something like `[$([N;+0](-[H])-[C;X4]-[C^2]=O)]`

Putting all of this together, you'd get:

```python
class PiBackboneNH(plf.interactions.PiCation):
    def __init__(self):
        super().__init__(cation="[$([N;+0](-[H])-[C;X4]-[C^2]=O)]")

fp = plf.Fingerprint(interactions=["PiBackboneNH", <insert any other interaction here>])
```

**Comment by DipBobDar** [comment]
Thanks for your suggestion.

I wanted to check intramolecular interaction in a peptide and was initerested in the hbond-pi interactions between N-H in the peptide bond and pi-system residues like Tyr, Phe, Trp. Is it possible to use the existing format to do this or I need to do something else.

Thanks in advance.
