### ISSUE TITLE
Empty Dataframe (no interaction detected warning) but fp object shows 11 interaction

### ISSUE THREAD

**Issue by SampurnaM** [chemosim-lab/ProLIF#175]
Hi Cédric,
I am trying to create fingerprints for a peptide in a protein and an antibody bound to the protein. The simulation is 100 ns, I am testing ProLIF only on the first 10 frames.
The fp.run is working, and writing to pickle, but not converting to dataframes ( I am getting:
  _**N_o interaction detected warnings.warn("No interaction detected") error_)**_  when running on Jupyter notebook.
I have gone through older resolved issues, and  also executed : 
print(fp.ifp[0])
print(fp.ifp)
(screenshot attached)

If this has already been resolved, or if I'm making some basic coding errors, please accept my apologies.
Sampurna

![image](https://github.com/chemosim-lab/ProLIF/assets/31826722/a9000aef-876c-4316-9247-10a3fa4a4119)
![image](https://github.com/chemosim-lab/ProLIF/assets/31826722/cd244bb1-83a7-4f5f-9cb5-3dcd568c2ca1)

**Comment by cbouy** [comment]
Hi,

Have you looked at your selections to check that they are set correctly? just printing your `peptide_chain` and `antibody` should display the number of atoms in there, if one of them is `0` then that's the place to look at.
Otherwise, a bit of a stretch but maybe there aren't any interaction in the first 10 frames of your trajectory, so you could try to slice your trajectory differently i.e. `selected_frames = u.trajectory[100:110]` to start later in the trajectory or `[:1000:100]` to sample 1 every 100 frames on the first 1000 frames.
