### ISSUE TITLE
Can't read the protein structure

### ISSUE THREAD

**Issue by meddwl** [chemosim-lab/ProLIF#18]
I tried to read the protein structure that I used for docking. I get the error that the standardization could not be completed within a reasonable number of iterations. What can I do?

File tipe: .pdbqt
Python: 3.9.2 

Code below run on ipython:
import prolif as plf
from rdkit import Chem
from rdkit.Chem import AllChem
import MDAnalysis as mda
from MDAnalysis.topology.guessers import guess_types

prot = mda.Universe("5es1_clustA.pdbqt")
guessed_elements = guess_types(prot.atoms.names)
prot.add_TopologyAttr('elements', guessed_elements)
prot = plf.Molecule.from_mda(prot)

Text error:

anaconda3/envs/rdkit-20/lib/python3.9/site-packages/MDAnalysis/coordinates/RDKit.py:492: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if isinstance(value, (float, np.float)):
anaconda3/envs/rdkit-20/lib/python3.9/site-packages/MDAnalysis/coordinates/RDKit.py:494: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif isinstance(value, (int, np.int)):
anaconda3/envs/rdkit-20/lib/python3.9/site-packages/MDAnalysis/coordinates/RDKit.py:416: UserWarning: No `bonds` attribute in this AtomGroup. Guessing bonds based on atoms coordinates
  warnings.warn(
anaconda3/envs/rdkit-20/lib/python3.9/site-packages/MDAnalysis/coordinates/RDKit.py:885: UserWarning: The standardization could not be completed within a reasonable number of iterations
  warnings.warn("The standardization could not be completed within a "
Segmentation fault

**Comment by cbouy** [comment]
Hi @meddwl ,

PDBQT files are a bit special to handle, as they do not satisfy either of the requirements for MDAnalysis to convert the input molecule (in your case the protein) to a proper RDKit molecule. Those requirements are either having bond orders and formal charges explicit in the file (usually the case with MOL2 files, but definitely not with PDBQT files), or having all hydrogen atoms explicit (and PDBQT files only have some but not all).
For it to work, you'll need your protein in a format that satisfies one of those requirements. If the file used to prepare your PDBQT file had all hydrogen atoms (like a PDB or MOL2 file) you can directly use that instead of the PDBQT. If you only have a PDB file that doesn't contain explicit hydrogens, or only some of them, you have 2 options:

- Read the PDB file with RDKit, it will automatically add the correct bond orders based on residues names:
```python
prot = Chem.MolFromPDBFile("protein.pdb", removeHs=False)
prot = Chem.AddHs(prot)
prot = plf.Molecule(prot)
```
- Or use h++ or another webserver/tool that will protonate the PDB file for you, and then:
```python
prot = Chem.MolFromPDBFile("protein.pdb", removeHs=False)
prot = plf.Molecule(prot)
```

You will likely have the same problem with the ligand, so please refer to the [documentation on using PDBQT files](https://prolif.readthedocs.io/en/latest/notebooks/how-to.html#Using-PDBQT-files) for more details.

Hope that solves the issue, but don't hesitate if you run into more problems
Cedric

**Comment by meddwl** [comment]
Thank you for your immediate response. Your answer helped me solve my problem
