### ISSUE TITLE
plf.display_residues(protein_mol)

### ISSUE THREAD

**Issue by milenamlakic** [chemosim-lab/ProLIF#196]
I have a problem with plf.display_residues(protein_mol). There are a lot of O2-, don't know how to fix, if you have idea I would be grateful..
![Issues](https://github.com/chemosim-lab/ProLIF/assets/159446573/67e7767f-234c-40ac-87ce-ce872d83ce61)

**Comment by cbouy** [comment]
Hi,

a few questions which might explain why this is happening:
- does your input file contain all hydrogen atoms explicitly? ProLIF requires all hydrogen atoms to be present
- does your input file contain any bond information? If you're reading from a PDB file, it's quite possible that only the ligand has them (or a cofactor...etc.), so you have to explicitly call `protein_atomgroup.guess_bonds()` before `protein_mol = plf.Molecule.from_mda(protein_atomgroup)`

**Comment by milenamlakic** [comment]
> Hi,
> 
> a few questions which might explain why this is happening:
> 
>     * does your input file contain all hydrogen atoms explicitly? ProLIF requires all hydrogen atoms to be present
> 
>     * does your input file contain any bond information? If you're reading from a PDB file, it's quite possible that only the ligand has them (or a cofactor...etc.), so you have to explicitly call `protein_atomgroup.guess_bonds()` before `protein_mol = plf.Molecule.from_mda(protein_atomgroup)`

Well the record from pdb in notepad++ is the same like in your github directory for rec and lig files, with hydrogens as well

there are mine:
[ligand.txt](https://github.com/chemosim-lab/ProLIF/files/14665169/ligand.txt)
[protein.txt](https://github.com/chemosim-lab/ProLIF/files/14665170/protein.txt)

**Comment by cbouy** [comment]
Ok I see where the problem is, your protein PDB file contains bond information for only a subset of residues (the non-standard ones like HIE), so the atoms without explicit bonds end up being assigned charges to satisfy valence rules.

You could either try removing the `CONECT` record at the end of your protein file, or simply forcing bond guessing calculation with:
```python
u = mda.Universe("protein.pdb", guess_bonds=True)
protein_mol = plf.Molecule.from_mda(u)
```
Or if you have the option, export the protein PDB file with all bonds explicit rather than just the ones for non-standard residues.

Please reopen this issue if you run into other related problems.
