### ISSUE TITLE
indices and parent_indices

### ISSUE THREAD

**Issue by Lili-Cao** [chemosim-lab/ProLIF#212]
Hi,

For the values of ligand and protein indices and parent_indices, where are the ints come from?
Are they the same order as the provided structure file?
Is the order start from 0 or it is the same as the provided atom number in the structure file?

Thanks!
Lili

**Comment by cbouy** [comment]
Hi,

The indices that are returned by ProLIF always start from 0. As to whether or not this matches with the index in the file, that will depend on the file format.

Regarding the difference between `indices` and `parent_indices`:
- `parent_indices` corresponds to the index of the atom in the input object that was used:
  - For the ligand if you used the `prolif.mol2/sdf/pdbqt_supplier` functions then that's the same as the input file.
  - For object constructed from MDAnalysis it depends: if you passed an entire MDAnalysis universe to `prolif.Molecule.from_mda` then that's also the same indices as the file, but if you passed an AtomGroup (i.e. what you obtain when you use `u.select_atoms`) then it will be indices based on that AtomGroup object (so from `0` to `atom_group.n_atoms - 1`) which won't necessarily match with your file. You can however convert the index in the prolif output to the index in the file with `atom_group[prolif_parent_index].index`.
- `indices` corresponds to the index of the atom in the corresponding "residue" object. For a small molecule ligand this should be the same as `parent_indices` since there's only a single residue.

Hopefully this answers your question, feel free to reopen the issue otherwise!
