### ISSUE TITLE
Hydrophobic interaction with an aromatic carbon bound to a nitrogen

### ISSUE THREAD

**Issue by papillot** [chemosim-lab/ProLIF#214]
The interaction between the Leu141 and the aromatic carbon in the following network plot quizzes me:
![Screenshot 2024-08-06 at 18 36 09](https://github.com/user-attachments/assets/6bd0c456-43bf-4232-aefc-4f753408bfd9)
The aromatic carbon is attached to a nitrogen which would give it a positive partial charge.
 
Looking at the corresponding SMARTS for this interaction:
```
[c,s,Br,I,S&H0&v2,$([D3,D4;#6])&!$([#6]~[#7,#8,#9])&!$([#6X4H0]);+0]
```
The lowercase `c` at the start of this pattern, with the `,` (OR) combinator means that any aromatic carbon satisfies the selector.
 The pattern `$([D3,D4;#6])&!$([#6]~[#7,#8,#9])&!$([#6X4H0])` takes into consideration any carbon (aromatic or aliphatic `#6`) and amongst other things, discards the ones that are bound to a nitrogen via any kind of bond (the `[#6]~[#7,#8,#9]` part)
This second pattern can not be evaluated for aromatic carbons because of the truthiness of `c` at the beginning of the SMARTS string.

Is there a specific consideration for always allowing aromatic carbons to make hydrophobic interactions?

**Comment by cbouy** [comment]
Hi,

> Is there a specific consideration for always allowing aromatic carbons to make hydrophobic interactions?

IIRC this part of the SMARTS comes from the RDKit pharmacophore definitions, and I think Pharmit (which I also used as an inspiration for some of the other SMARTS) also accepts any aromatic atom as hydrophobic.

Plus to take these sorts of effects into account a bit more accurately, we'd have to consider how the different substituents may activate or deactivate the ring so that would be quite complicated to generalise and express in a SMARTS pattern.

If need be you can easily modify the SMARTS (and any other interaction parameter) being used to fit your case:
```python
fp = plf.Fingerprint(
    parameters={
        "Hydrophobic": {
            "hydrophobic": "<custom SMARTS here>"
        }
    }
)
```

Please close the issue if this answers your question

**Comment by papillot** [comment]
Thanks for the detailed answer!
