### ISSUE TITLE
Metal acceptor

### ISSUE THREAD

**Issue by DrrDom** [chemosim-lab/ProLIF#48]
The tool cannot find a metal acceptor. For example the structure of 3zuk has Zn ion and a ligand coordinating with it by S=O group. It finds only contacts with the protein. Is there some option to enable metal center to be considered as a protein part?

I looked at the documentation and found SMART for metal_acceptor which puzzled me. Could you explain what this `{1-}` mean in `[O,N,-{1-};!+{1-}]`?

I use prolif version 0.3.4

Thank you!

[3zuk.zip](https://github.com/chemosim-lab/ProLIF/files/8304461/3zuk.zip)
.

**Comment by cbouy** [comment]
Hi @DrrDom,

The `{1-}` is what is called a "range query", it's an extension of the Daylight SMARTS available in RDKit (see [here](https://www.rdkit.org/docs/RDKit_Book.html#smarts-support-and-extensions) for more info).
In that case, it means "1 or more", and since it's just before a `-`, the whole expression `-{1-}` means "with 1 or more negative charge(s)", a.k.a any anion.
Similarly `!+{1-}` means "no cation".

I had a look at your files, thanks for providing them. I couldn't reproduce the issue, here's the code that I used.
Since the protein is quite large, I selected only residues within 10A of the center of your ligand so that it runs more quickly, but you can change that if you want.

```python
import MDAnalysis as mda
import prolif as plf
from rdkit import Chem

# load ligand
lig = Chem.MolFromMolFile("ligand_h.mol", removeHs=False)
lig = plf.Molecule.from_rdkit(lig)
print("Ligand centroid:", list(lig.centroid))
# prints [58.748054054054066, 67.9504864864865, 9.34735135135135]

# vdwradii for Zn is set to 0 to prevent MDAnalysis from making covalent bonds
# between Zn and other atoms
u = mda.Universe("3zuk.pdb", guess_bonds=True, vdwradii={"Zn": 0, "Cl":1})
# create selection around where your ligand is. Includes the Zn ion
prot = plf.Molecule.from_mda(u, "byres point 58.7 67.9 9.3 10")

# create fingerprint. Make sure to include MetalAcceptor, since it's not used by default
fp = plf.Fingerprint([
    'Hydrophobic', 'HBDonor', 'HBAcceptor',
    'Anionic', 'Cationic', 'CationPi', 'PiCation',
    'PiStacking', 'MetalAcceptor'])
fp.run_from_iterable([lig], prot)
df = fp.to_dataframe()
df
```

This will detect the ligand-Zn interaction as expected.

I also just realized that the current definition for the "ligand" in the metal coordination doesn't include aromatic nitrogens. Rookie mistake from my part! :) I'll update the ligand definition to `[O,#7,-{1-};!+{1-}]` in future updates.

Hopefully that solves your issue!

Cédric

**Comment by DrrDom** [comment]
Thank you!
I found the mistake in my code. I expected that the program will search for all contacts by default, but I have to pass them explicitly at Fingerprint initialization.

Actually, I use RDKit to read protein and it works faster than with MDA. For future users, set `sanitize` to False, otherwise RDKit may return an error for metal-containing proteins.

```python
plf_prot = plf.Molecule(Chem.MolFromPDBFile(protein_filename, removeHs=False, sanitize=False))
fp = plf.Fingerprint(['Hydrophobic', 'HBDonor', 'HBAcceptor','Anionic', 'Cationic', 'CationPi', 'PiCation', 'PiStacking', 'MetalAcceptor'])
fp.run_from_iterable([plf.Molecule.from_rdkit(lig)], plf_prot)
df = fp.to_dataframe()
```

Pavel.
