### ISSUE TITLE
Howtorun?

### ISSUE THREAD

**Issue by DDGmichigan** [chemosim-lab/ProLIF#52]
Hi all
I successfully installed PROLIF and I did conda activate prolif and I see the virtual environment on.
I am new to python scripts, can someone explain what is the next step to check I did the installation correctly without bugs?
Do I now copy the simple lines of code inside a test.py and run it inside the conda environment?
 I see the tutorial has these:
import MDAnalysis as mda
import prolif as plf
# load trajectory
u = mda.Universe(plf.datafiles.TOP, plf.datafiles.TRAJ)
# create selections for the ligand and protein
lig = u.atoms.select_atoms("resname LIG")
prot = u.atoms.select_atoms("protein")
lig, prot

So should I save the above lines inside test.py and then run python3 test.py from my terminal?
How do I give it the arguments? I have a test.pdb which is a collection of snapshots of a protein-ligand MD trajectory and I am interested to see the main interactions happening in these 20ns of MD production output. I also have a trajectory.nc file saved in my terminal.
Please help me.
Thanks!

**Comment by cbouy** [comment]
Hi @DDGmichigan,

There's no need to test the installation, but if you're unsure about using the correct virtual env where prolif is installed, you could run this command: `python -c 'import prolif; print(f"ProLIF version {prolif.__version__}")'` which imports the library and prints the version.
(if it output "0+unknown" it's fine, it just means you've installed the current development version instead of a specific release, but they're both stable so no worries here).

Assuming you've already centered the protein at the middle of your simulation's box in your trajectory file, here's an example script to run the default analysis. Note that you only need to modify what's between `# PARAMETERS #` and `# ANALYSIS #`. 
This script will produce 3 files in the output directory: 
- `ifp.csv` the interaction fingerprint in CSV format, to analyse with whatever programming language/analysis software you're familiar with
- `dataframe.pkl` the python `pandas.DataFrame` object as a binary file, in case you want to use Python in the future
- `dataframe_atom_indices.pkl` same as above but with the ligand and protein atom indices responsible for the each interaction

```python
#!/usr/bin/env python
from pathlib import Path
import MDAnalysis as mda
import numpy as np
import prolif as plf

# PARAMETERS #

OUTPUT_FOLDER = "."
TOPOLOGY = "test.pdb"
TRAJECTORY = "trajectory.nc"
LIGAND_SELECTION = "resname LIG"  # the residue name for your ligand
                                  # you can also use "resid 123" if you prefer using residue numbers
PROTEIN_SELECTION = "protein"  # "protein" automatically selects the protein for you
# if unsure, use None for the following parameters, otherwise use an integer
START = 0  # start the analysis at this frame of your trajectory
STOP = None  # stop the analysis at this frame
STEP = 10  # use one frame every STEP frames for the analysis

# ANALYSIS #

print("Preparation step")

# load MD simulation
u = mda.Universe(TOPOLOGY, TRAJECTORY)

# create selections for the ligand and protein
lig = u.atoms.select_atoms(LIGAND_SELECTION)
prot = u.atoms.select_atoms(PROTEIN_SELECTION )
# guess bonds if absent from topology file
if not hasattr(u.atoms, "bonds"):
    print("Bonds absent in topology file, automatically guessing them")
    u.select_atoms("group lig or group prot", lig=lig, prot=prot).guess_bonds()

# use default interactions
fp = plf.Fingerprint()
print(f"Interactions that will be evaluated: {list(fp.interactions.keys())}")

print("Running IFP analysis")
fp.run(u.trajectory[START:STOP:STEP], lig, prot)

print("Analysis finished, exporting results")
df = fp.to_dataframe(dtype=np.uint8)
RESULTS = Path(OUTPUT_FOLDER)
RESULTS.mkdir(parents=True, exist_ok=True)
df.to_pickle(str(RESULTS / "dataframe.pkl"))
df.to_csv(str(RESULTS / "ifp.csv"))
fp.to_dataframe(return_atoms=True).to_pickle(str(RESULTS / "dataframe_atom_indices.pkl"))
print("Done")
```

The code is not parallelized yet, so it might take a while, especially on the first frame since it needs to do some preliminary preparation steps. If it's taking too long, consider using a larger STEP. There's a progress bar to track down the progress of the analysis.

Save this script as `ifp_analysis.py` for example, and run from your terminal with `python ifp_analysis.py`

Hope that helps,
Cedric

**Comment by DDGmichigan** [comment]
Hi Cedric,
My trajectory is in nc format and I have centered the protein in the center of the box.
I am not sure how to provide the arguments: I have a the topology file, the trajectory.nc file, and the protein ligand solvated pdb file.
Do I need anything else to run this python script?

Many thanks
Debarati

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by cbouy** [comment]
In terms of input you just the topology and trajectory files, you don't even need the PDB if you use the topology file directly.
However you still need to specify to which residue your ligand corresponds to (either through its residue name or number) and a few other parameters (see below)

For the arguments, they are directly included in the script that I provided.
More specifically, it's the following part of the code that you may have to modify to match your file names...etc.

```python
OUTPUT_FOLDER = "."
TOPOLOGY = "./test.pdb"
TRAJECTORY = "./trajectory.nc"
LIGAND_SELECTION = "resname LIG"  # the residue name for your ligand
                                  # you can also use "resid 123" if you prefer using residue numbers
PROTEIN_SELECTION = "protein"  # "protein" automatically selects the protein for you
# if unsure, use None (without quotes) for the following parameters, otherwise use an integer
START = 0  # start the analysis at this frame of your trajectory
STOP = None  # stop the analysis at this frame
STEP = 10  # use one frame every STEP frames for the analysis
```

In doubt, use `START=0`, `STOP=3` and `STEP=1` to compute the fingerprint on the 3 first frames of your trajectory, and have a look at the `ifp.csv` output file to check that everything worked correctly.
