### ISSUE TITLE
Example code LigPlot for PPI

### ISSUE THREAD

**Issue by blacktanktop** [chemosim-lab/ProLIF#58]
I would like to do a LigPlot of protein and peptide, is it possible?
If it is possible, I would like you to provide a sample code using PDB file, for example, 1YCR (MDM2 /p53 peptide). (I would appreciate it if you could provide a notebook with an example of LigPlot from a PDB file we can get from PDB, instead of reading from package dataset.)

**Comment by cbouy** [comment]
Hi @blacktanktop,

For now it's only possible to generate the LigPlot for a "typical" ligand (i.e. a molecule with a single residue).
However there's a workaround in #51 which basically replaces the residues name and number of your peptide so that it looks like it's a single residue molecule.

You cannot directly use a PDB file straight from the PDB, you will need to add explicit hydrogen atoms to it (using webservers such as [H++](http://newbiophysics.cs.vt.edu/H++/uploadpdb.php) or propka).

Once you have your protonated PDB file, you should be able to run the analysis and generate the LigPlot with:

```python

import prolif as plf
from prolif.plotting.network import LigNetwork
import MDAnalysis as mda
import numpy as np

u = mda.Universe("1YCR_protonated.pdb", guess_bonds=True)

# prepare selections for peptide and protein
### these selections may change depending on your input and how the file was prepared.
### here I'm selecting fragments 0 and 1 manually because segment IDs were stripped during file preparation
peptide = u.atoms[u.atoms.fragindices == 0]
prot = u.atoms[u.atoms.fragindices == 1]
# assign peptide to smaller selection
if prot.n_atoms < peptide.n_atoms:
    prot, peptide = peptide, prot

# trick to make the LigPlot work with peptide
peptide.residues.resnames = np.array(["lig"]*len(peptide.residues.resnames))
peptide.residues.resids = np.array([1]*len(peptide.residues.resids)

# run analysis
fp = plf.Fingerprint()
fp.run(u.trajectory, peptide, prot, n_jobs=1)
df = fp.to_dataframe(return_atoms=True)

# create ligplot
mol = plf.Molecule.from_mda(peptide)
# you might need to tweak `rotation` and `molsize` to your liking
plot = LigNetwork.from_ifp(df, mol, kind="frame", frame=0, match3D=False, rotation=-90, molsize=45)
plot.save("ligplot.html")
```
And then just display the `ligplot.html` file with your web browser (it may take a few seconds to load).

Hope that helps,
Cédric

**Comment by blacktanktop** [comment]
Thank you for sample code.
I changed the plot options slightly to get the conformation correct, but it looks like I got it somewhat as expected.
<img width="813" alt="スクリーンショット 2022-06-14 20 39 58" src="https://user-images.githubusercontent.com/7370243/173568859-f1cc576f-ed15-458c-bd00-74796ffa8c2f.png">

**Comment by blacktanktop** [comment]
I thought it would be better to be able to plot the PDB conformation as it is.

**Comment by cbouy** [comment]
Glad it worked, and yes, the layout is not ideal, that's why I used ` match3D=False` in the snippet above otherwise I find it a bit difficult to read.

I agree that users should be able to use the conformation (2D or 3D) that's already in the molecule rather than only having the choice between "flattening" the 3D coords or generating a 2D layout from scratch.
It shouldn't be too much trouble for me to implement.
