### ISSUE TITLE
How to extract the list of interacting Amino Acid Residues between the protein and the ligand through PDBQT

### ISSUE THREAD

**Issue by eschoo** [chemosim-lab/ProLIF#80]
I have a Collection (in .tar) that is composed of hundreds of PDBQT files of the resulting docking poses between a protein and a ligand through an HPC Cluster. How would I go about extracting a list of all of the interacting amino acid residues for each of the docked PDBQT files (around 1 million docked files)?

**Comment by cbouy** [comment]
Hi @eschoo,

Have you looked at [this part of the documentation](https://prolif.readthedocs.io/en/latest/notebooks/how-to.html#Using-PDBQT-files)?
The only catch is that you'll require either a MOL2 file or SMILES to map the bond orders and formal charges to your PDBQT poses for each ligand.

Best, Cédric

**Comment by eschoo** [comment]
Hi @cbouy ,

Thank you for the help! My issue is how I would go about this for a large collection of PDBQT files with docked compounds. Would ProLIF have a way of looking into each .tar collection, which is composed of thousands of PDBQT files, and obtain the amino acid residues for each of the PDBQT files and document them? Thank you!

**Comment by cbouy** [comment]
Sorry for the very late response, I'm quite busy these days!

ProLIF doesn't have a way to directly read files from a tar collection, but the Python standard library has a `tarfile` module that might have helped. Unfortunately, MDAnalysis (the underlying library used by the `prolif.pdbqt_supplier` class) does not support multi-model PDBQT files, you have to split them so that they only contain a single docking pose per file. If you've used Vina for docking, there's a `vina_split` command that you could use to split poses into single files, but it would defeat the purpose of reading directly from a tar file :/
