### ISSUE TITLE
Only showing hydrophobic interactions

### ISSUE THREAD

**Issue by davidcooper7** [chemosim-lab/ProLIF#96]
Hello. I'm having trouble getting the fingerprints to show me any interactions other than hydrophobic. I know there are hydrogen bond interactions(see image from pyMOL). Any help in the right direction would be great.

![help1](https://user-images.githubusercontent.com/117563200/200404217-9efdc37d-268c-460d-821c-9c117a2823df.png)
![help2](https://user-images.githubusercontent.com/117563200/200404219-dadbb8a2-80ed-495c-8713-72b6afa37644.png)

**Comment by cbouy** [comment]
Hi @davidcooper7,

I've just made a new release of ProLIF (v1.1.0) which includes some major changes to the interaction definitions, as well as some fixes in the `pdbqt_supplier`. Could you try installing it and see if it works?

Cheers,
Cédric

**Comment by davidcooper7** [comment]
Cedric,

Thanks for the update! The interactions appear to be much more consistent
with what we can see visually between our ligand and protein. However, with
the inclusion of Van der Waals interactions, there appears to be where
there is Van der Waals contact and hydrogen bonding between the same
residues and atoms of the ligands. This seems a little counterintuitive,
could you help me understand how to interpret this?

Thanks
David

**Comment by cbouy** [comment]
Hi David,

Sorry for not answering you back, I had forgotten about this issue until I decided to do a bit of triage today...

When calculating each interaction type, ProLIF does not take other interactions into account, so the same group of atoms could potentially be labelled as involved simultaneously in hydrogen bonding and a contact.

Because of the attractive nature of the Hbonding, having it labelled as a contact is relatively common, but there's no way to distinguish the contact from a clash in the current code (unless you define your own interaction).

So the fingerprint code will not prioritize any interaction other another, but you could do this as a postprocessing step in the resulting dataframe since you can have access to atom indices in both residue and ligand.

If this does not answer your question feel free to reopen the issue!

Best,
Cedric
